/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/knowledge/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Extract knowledge records from textbook text */
        post: operations["extract_knowledge_api_knowledge_extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 持久化数学 RAG 问答 */
        post: operations["chat_v1_api_v1_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Conversations */
        get: operations["list_conversations_api_v1_conversations_get"];
        put?: never;
        /** Create Conversation */
        post: operations["create_conversation_api_v1_conversations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Conversation */
        get: operations["get_conversation_api_v1_conversations__conversation_id__get"];
        put?: never;
        post?: never;
        /** Delete Conversation */
        delete: operations["delete_conversation_api_v1_conversations__conversation_id__delete"];
        options?: never;
        head?: never;
        /** Update Conversation */
        patch: operations["update_conversation_api_v1_conversations__conversation_id__patch"];
        trace?: never;
    };
    "/api/v1/conversations/{conversation_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Messages */
        get: operations["list_messages_api_v1_conversations__conversation_id__messages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_api_v1_documents_get"];
        put?: never;
        /** Upload Document */
        post: operations["upload_document_api_v1_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingestion-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ingestion Jobs */
        get: operations["list_ingestion_jobs_api_v1_ingestion_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingestion-jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ingestion Job */
        get: operations["get_ingestion_job_api_v1_ingestion_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingestion-jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Ingestion Job */
        post: operations["cancel_ingestion_job_api_v1_ingestion_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingestion-jobs/{job_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Ingestion Job */
        post: operations["retry_ingestion_job_api_v1_ingestion_jobs__job_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Knowledge Items */
        get: operations["list_knowledge_items_api_v1_knowledge_items_get"];
        put?: never;
        /** Create Knowledge Item */
        post: operations["create_knowledge_item_api_v1_knowledge_items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge-items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Knowledge Item */
        get: operations["get_knowledge_item_api_v1_knowledge_items__item_id__get"];
        put?: never;
        post?: never;
        /** Delete Knowledge Item */
        delete: operations["delete_knowledge_item_api_v1_knowledge_items__item_id__delete"];
        options?: never;
        head?: never;
        /** Update Knowledge Item */
        patch: operations["update_knowledge_item_api_v1_knowledge_items__item_id__patch"];
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 兼容健康检查 */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 进程存活检查 */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 应用就绪检查 */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgenticPlan */
        AgenticPlan: {
            /**
             * Retrieval Queries
             * @description 规划生成的检索子问题
             */
            retrieval_queries?: string[];
            /**
             * Strategy
             * @description 检索规划策略说明
             * @default
             */
            strategy: string;
        };
        /**
         * AuthUserRead
         * @description 认证端点冻结的最小用户资源。
         */
        AuthUserRead: {
            /** Email */
            email: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Role */
            role: string;
            /** Status */
            status: string;
            /** Username */
            username: string;
        };
        /** Body_upload_document_api_v1_documents_post */
        Body_upload_document_api_v1_documents_post: {
            /** Category */
            category?: string | null;
            /** File */
            file: string;
        };
        /** ChatV1Request */
        ChatV1Request: {
            /**
             * Client Request Id
             * Format: uuid
             */
            client_request_id: string;
            /**
             * Conversation Id
             * Format: uuid
             */
            conversation_id: string;
            /** Question */
            question: string;
            /** Top K */
            top_k?: number | null;
        };
        /** ChatV1Response */
        ChatV1Response: {
            /** @description 检索规划信息 */
            agentic_plan?: components["schemas"]["AgenticPlan"] | null;
            /**
             * Answer
             * @description 最终回答
             */
            answer: string;
            /**
             * Answer Message Id
             * Format: uuid
             */
            answer_message_id: string;
            /**
             * Client Request Id
             * Format: uuid
             */
            client_request_id: string;
            /**
             * Conversation Id
             * Format: uuid
             */
            conversation_id: string;
            /**
             * Question
             * @description 用户当前问题
             */
            question: string;
            /**
             * Question Message Id
             * Format: uuid
             */
            question_message_id: string;
            /**
             * Rag Run Id
             * Format: uuid
             */
            rag_run_id: string;
            /**
             * Reasoning Content
             * @description 模型额外的推理内容（可选）
             */
            reasoning_content?: string | null;
            /**
             * References
             * @description 检索到的参考知识
             */
            references?: components["schemas"]["ReferenceItem"][];
            /**
             * Related Questions
             * @description 推荐追问
             */
            related_questions?: string[];
            /**
             * Steps
             * @description 回答步骤
             */
            steps?: string[];
            /**
             * Used Knowledge
             * @description 本次实际使用到的知识点标题
             */
            used_knowledge?: string[];
        };
        /** ConversationCreate */
        ConversationCreate: {
            /**
             * Title
             * @default 新对话
             */
            title: string;
        };
        /** ConversationPage */
        ConversationPage: {
            /** Items */
            items: components["schemas"]["ConversationRead"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** ConversationRead */
        ConversationRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "archived";
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ConversationUpdate */
        ConversationUpdate: {
            /** Status */
            status?: ("active" | "archived") | null;
            /** Title */
            title?: string | null;
        };
        /**
         * DocumentAccepted
         * @description 上传成功后返回的文档及其待执行任务。
         */
        DocumentAccepted: {
            document: components["schemas"]["DocumentRead"];
            job: components["schemas"]["IngestionJobRead"];
        };
        /**
         * DocumentPage
         * @description 文档分页响应。
         */
        DocumentPage: {
            /** Items */
            items: components["schemas"]["DocumentRead"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /**
         * DocumentRead
         * @description 不暴露受控存储路径的文档表示。
         */
        DocumentRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Mime Type */
            mime_type: string;
            /** Original Name */
            original_name: string;
            /** Owner Id */
            owner_id: string | null;
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "processing" | "ready" | "failed" | "archived";
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** App Name */
            app_name: string;
            /**
             * Status
             * @default ok
             */
            status: string;
        };
        /**
         * IngestionJobPage
         * @description 导入任务偏移分页响应。
         */
        IngestionJobPage: {
            /** Items */
            items: components["schemas"]["IngestionJobRead"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /**
         * IngestionJobRead
         * @description 不暴露重试载荷的导入任务表示。
         */
        IngestionJobRead: {
            /** Attempt Count */
            attempt_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Document Id */
            document_id: string | null;
            /** Error Code */
            error_code?: string | null;
            /** Error Message */
            error_message?: string | null;
            /** Finished At */
            finished_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Job Type
             * @enum {string}
             */
            job_type: "text" | "pdf" | "web" | "reindex";
            /** Progress */
            progress: number;
            /** Requested By */
            requested_by: string | null;
            /** Started At */
            started_at: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "completed" | "failed" | "cancelled";
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** KnowledgeExtractRequest */
        KnowledgeExtractRequest: {
            /**
             * Category
             * @description Optional category hint
             */
            category?: string | null;
            /**
             * Save
             * @description Legacy JSONL writes are no longer supported
             * @default false
             */
            save: boolean;
            /**
             * Text
             * @description Text excerpt from a math textbook
             */
            text: string;
        };
        /** KnowledgeExtractResponse */
        KnowledgeExtractResponse: {
            /** Next Steps */
            next_steps?: string[];
            /** Records */
            records: components["schemas"]["KnowledgeRecord"][];
            /**
             * Saved Count
             * @default 0
             */
            saved_count: number;
        };
        /**
         * KnowledgeItemCreate
         * @description 管理员创建知识条目的请求模型。
         */
        KnowledgeItemCreate: {
            /** Category */
            category: string;
            /** Content */
            content: string;
            /**
             * Difficulty
             * @enum {string}
             */
            difficulty: "easy" | "medium" | "hard";
            /**
             * Example
             * @default
             */
            example: string;
            /** Keywords */
            keywords: string[];
            /** Steps */
            steps: string[];
            /** Title */
            title: string;
            /**
             * Visibility
             * @default public
             * @enum {string}
             */
            visibility: "public" | "private";
        };
        /**
         * KnowledgeItemPage
         * @description 知识条目分页响应。
         */
        KnowledgeItemPage: {
            /** Items */
            items: components["schemas"]["KnowledgeItemRead"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /**
         * KnowledgeItemRead
         * @description 知识条目的安全公开表示。
         */
        KnowledgeItemRead: {
            /** Category */
            category: string;
            /** Content */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Difficulty
             * @enum {string}
             */
            difficulty: "easy" | "medium" | "hard";
            /** Example */
            example: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Keywords */
            keywords: string[];
            /** Legacy Id */
            legacy_id: string | null;
            /** Owner Id */
            owner_id: string | null;
            /** Revision */
            revision: number;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "indexing" | "ready" | "failed" | "archived";
            /** Steps */
            steps: string[];
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Visibility
             * @enum {string}
             */
            visibility: "public" | "private";
        };
        /**
         * KnowledgeItemUpdate
         * @description 管理员更新知识条目的请求模型。
         */
        KnowledgeItemUpdate: {
            /** Category */
            category?: string | null;
            /** Content */
            content?: string | null;
            /** Difficulty */
            difficulty?: ("easy" | "medium" | "hard") | null;
            /** Example */
            example?: string | null;
            /** Keywords */
            keywords?: string[] | null;
            /** Revision */
            revision: number;
            /** Steps */
            steps?: string[] | null;
            /** Title */
            title?: string | null;
            /** Visibility */
            visibility?: ("public" | "private") | null;
        };
        /** KnowledgeRecord */
        KnowledgeRecord: {
            /**
             * Category
             * @description Knowledge category
             */
            category: string;
            /**
             * Content
             * @description Core explanation
             */
            content: string;
            /**
             * Difficulty
             * @description easy / medium / hard
             */
            difficulty: string;
            /**
             * Example
             * @description Example or application
             * @default
             */
            example: string;
            /**
             * Id
             * @description Knowledge item id, for example k0001
             */
            id: string;
            /**
             * Keywords
             * @description Keywords
             */
            keywords?: string[];
            /**
             * Steps
             * @description Understanding or solving steps
             */
            steps?: string[];
            /**
             * Title
             * @description Knowledge point title
             */
            title: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /** MessagePage */
        MessagePage: {
            /** Items */
            items: components["schemas"]["MessageRead"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** MessageRead */
        MessageRead: {
            /** Content */
            content: string;
            /**
             * Conversation Id
             * Format: uuid
             */
            conversation_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Model Metadata */
            model_metadata: {
                [key: string]: unknown;
            };
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant" | "system";
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "completed" | "failed";
        };
        /** ReferenceItem */
        ReferenceItem: {
            /**
             * Answer Context
             * @description 面向回答构造的上下文文本
             * @default
             */
            answer_context: string;
            /**
             * Category
             * @description 知识类别
             */
            category: string;
            /**
             * Chunk Id
             * @description chunk 唯一标识
             */
            chunk_id: string;
            /**
             * Content
             * @description 知识点核心内容
             * @default
             */
            content: string;
            /**
             * Difficulty
             * @description 难度：easy / medium / hard
             */
            difficulty: string;
            /**
             * Example
             * @description 示例或应用场景
             * @default
             */
            example: string;
            /**
             * Index
             * @description 旧版兼容字段；pgvector 路径为空
             */
            index?: number | null;
            /**
             * Keywords
             * @description 关键词列表
             */
            keywords?: string[];
            /**
             * Metadata
             * @description 附加元数据
             */
            metadata?: {
                [key: string]: unknown;
            };
            /**
             * Rank
             * @description 检索排序名次，从 1 开始
             */
            rank: number;
            /**
             * Retrieval Text
             * @description 面向向量检索的拼接文本
             * @default
             */
            retrieval_text: string;
            /**
             * Score
             * @description 向量检索得分
             */
            score: number;
            /**
             * Source Id
             * @description 原始知识点 id
             */
            source_id: string;
            /**
             * Source Line
             * @description 原始 JSONL 所在行号
             */
            source_line?: number | null;
            /**
             * Steps
             * @description 理解或解题步骤
             */
            steps?: string[];
            /**
             * Title
             * @description 知识点标题
             */
            title: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    extract_knowledge_api_knowledge_extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeExtractRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeExtractResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUserRead"];
                };
            };
        };
    };
    chat_v1_api_v1_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatV1Request"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatV1Response"];
                };
            };
            /** @description Session 无效 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description CSRF 或来源校验失败 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 会话不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 会话或幂等请求状态冲突 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 请求校验失败 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_conversations_api_v1_conversations_get: {
        parameters: {
            query?: {
                status?: "active" | "archived";
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_conversation_api_v1_conversations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_api_v1_conversations__conversation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_conversation_api_v1_conversations__conversation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_conversation_api_v1_conversations__conversation_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_messages_api_v1_conversations__conversation_id__messages_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessagePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_api_v1_documents_get: {
        parameters: {
            query?: {
                status?: ("pending" | "processing" | "ready" | "failed" | "archived") | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_document_api_v1_documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_api_v1_documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ingestion_jobs_api_v1_ingestion_jobs_get: {
        parameters: {
            query?: {
                status?: ("pending" | "running" | "completed" | "failed" | "cancelled") | null;
                job_type?: ("text" | "pdf" | "web" | "reindex") | null;
                document_id?: string | null;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionJobPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ingestion_job_api_v1_ingestion_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionJobRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_ingestion_job_api_v1_ingestion_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionJobRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_ingestion_job_api_v1_ingestion_jobs__job_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionJobRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_knowledge_items_api_v1_knowledge_items_get: {
        parameters: {
            query?: {
                status?: ("draft" | "indexing" | "ready" | "failed" | "archived") | null;
                visibility?: ("public" | "private") | null;
                category?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeItemPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_knowledge_item_api_v1_knowledge_items_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeItemCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeItemRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_knowledge_item_api_v1_knowledge_items__item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeItemRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_knowledge_item_api_v1_knowledge_items__item_id__delete: {
        parameters: {
            query: {
                revision: number;
            };
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_knowledge_item_api_v1_knowledge_items__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeItemUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeItemRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
